apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  DATABASE_URL: "postgres://toggle:HB0OmIt7XvqT3vcBpiUimFVY@togglemaster-auth-db.curuk0yy63p6.us-east-1.rds.amazonaws.com:5432/auth_db?sslmode=require"
  MASTER_KEY: "a22fkAgap2o23EqlBscjaltt"
  SERVICE_API_KEY: "8jKc3Uqp450tztzdQ5LV5sGYr1llW6Wj"
---
apiVersion: v1
kind: Secret
metadata:
  name: flag-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  DATABASE_URL: "postgres://toggle:HB0OmIt7XvqT3vcBpiUimFVY@togglemaster-flags-db.curuk0yy63p6.us-east-1.rds.amazonaws.com:5432/flags_db?sslmode=require"
  SERVICE_API_KEY: "8jKc3Uqp450tztzdQ5LV5sGYr1llW6Wj"
---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  DATABASE_URL: "postgres://toggle:HB0OmIt7XvqT3vcBpiUimFVY@togglemaster-targeting-db.curuk0yy63p6.us-east-1.rds.amazonaws.com:5432/targeting_db?sslmode=require"
  SERVICE_API_KEY: "8jKc3Uqp450tztzdQ5LV5sGYr1llW6Wj"
---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  REDIS_URL: "redis://togglemaster-redis.bkfput.ng.0001.use1.cache.amazonaws.com:6379/0"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/889629667863/togglemaster-evaluation-events"
  SERVICE_API_KEY: "8jKc3Uqp450tztzdQ5LV5sGYr1llW6Wj"
---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/889629667863/togglemaster-evaluation-events"
  SERVICE_API_KEY: "8jKc3Uqp450tztzdQ5LV5sGYr1llW6Wj"
