apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: togglemaster

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - auth-service.yaml
  - flag-service.yaml
  - targeting-service.yaml
  - evaluation-service.yaml
  - analytics-service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/part-of: togglemaster
