apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
data:
  # Replace these placeholder values with the base64 outputs emitted by Terraform.
  DATABASE_URL: UkVQTEFDRV9NRQ==
  MASTER_KEY: UkVQTEFDRV9NRQ==
  SERVICE_API_KEY: UkVQTEFDRV9NRQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: flag-service-secret
type: Opaque
data:
  DATABASE_URL: UkVQTEFDRV9NRQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secret
type: Opaque
data:
  DATABASE_URL: UkVQTEFDRV9NRQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
type: Opaque
data:
  REDIS_URL: UkVQTEFDRV9NRQ==
  AWS_SQS_URL: UkVQTEFDRV9NRQ==
  SERVICE_API_KEY: UkVQTEFDRV9NRQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
type: Opaque
data:
  AWS_SQS_URL: UkVQTEFDRV9NRQ==
