apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      serviceAccountName: analytics-service-sa
      containers:
        - name: analytics-service
          image: REPLACE_ME_ECR_URI/analytics-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8005
          env:
            - name: PORT
              value: "8005"
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: AWS_REGION
            - name: AWS_DYNAMODB_TABLE
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: AWS_DYNAMODB_TABLE
            - name: AWS_SQS_URL
              valueFrom:
                secretKeyRef:
                  name: analytics-service-secret
                  key: AWS_SQS_URL
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - name: http
      port: 80
      targetPort: http
