apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: targeting-service
  template:
    metadata:
      labels:
        app: targeting-service
    spec:
      containers:
        - name: targeting-service
          image: REPLACE_ME_ECR_URI/targeting-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8003
          env:
            - name: PORT
              value: "8003"
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: AUTH_SERVICE_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: targeting-service-secret
                  key: DATABASE_URL
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: targeting-service-secret
                  key: SERVICE_API_KEY
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: targeting-service
spec:
  type: ClusterIP
  selector:
    app: targeting-service
  ports:
    - name: http
      port: 80
      targetPort: http
